In [20]:
import pandas as pd
import numpy as np
import names as n

In [602]:
pd.read_excel('Data1.xlsx')

,Unnamed: 0,Имя,Фамилия,Возраст,№ выступления,Баллы,Призовое место,Телефон
0,1,Lucienne,Hopkins,9,7,20,10,+7(268)865-27-26
1,2,Annette,Doyle,13,5,40,9,+7(137)886-83-57
2,3,Carolyn,Almanza,13,10,47,8,+7(335)474-30-58
3,4,Susie,Snyder,8,8,55,7,+7(211)416-55-26
4,5,Luella,Linton,7,9,55,6,+7(840)979-52-64
5,6,Ilene,Hibbler,10,3,56,5,+7(773)361-83-74
6,7,Lyman,Jackson,18,1,64,4,+7(767)697-26-53
7,8,Anita,Paya,13,6,96,3,+7(685)290-99-86
8,9,Corey,Ward,13,2,96,2,+7(635)743-81-45
9,10,Marion,Rodriguez,14,4,98,1,+7(227)475-46-19

In [576]:
index = np.arange(1, 11)

frame = {'Имя': [n.get_first_name() for i in range(len(index))],
        'Фамилия': [n.get_last_name() for i in range(len(index))],
        'Возраст': [np.random.randint(5,20) for i in range(len(index))]}

frame['№ выступления'] = []
while len(frame['№ выступления']) != len(index):
    for i in range(len(index)):
        k = np.random.randint(i,11)
        if k not in frame['№ выступления'] and k != 0:
            frame['№ выступления'].append(k)
        
frame['Баллы'] = [np.random.randint(20,100) for i in range(len(index))]

frame['Призовое место'] = []
k = 10
p = 11
frame['Баллы'].sort()
for i in range(len(frame['Баллы'])):
    if k <= frame['Баллы'][i]:
        k = frame['Баллы'][i]
        p -= 1
        frame['Призовое место'].append(p)
        
frame['Телефон'] = [("+7" + "(" + str(np.random.randint(100, 1000)) + ")" + str(np.random.randint(100, 1000)) + "-" + str(np.random.randint(10, 100)) + "-" + str(np.random.randint(10, 100))) for i in range(len(index))]

df = pd.DataFrame(frame, index)

df.to_excel('Data2.xlsx')

In [603]:
df.sort_values(by = 'Призовое место')

,Имя,Фамилия,Возраст,№ выступления,Баллы,Призовое место,Телефон,Compare
10,Marian,Schleider,14,1,93,1,+7(438)778-94-17,NaN
9,Shirley,Castillo,14,3,82,2,+7(608)889-72-21,True
8,Susan,Mays,12,4,71,3,+7(911)405-92-80,True
7,Anthony,Vanpelt,6,5,67,4,+7(756)293-98-74,True
6,Wilber,Bishop,5,8,60,5,+7(320)828-77-31,True
5,Anna,Barton,13,6,49,6,+7(885)328-88-19,True
4,Debra,Simpson,18,7,47,7,+7(463)229-52-75,True
3,Donald,Roman,5,10,43,8,+7(403)977-83-87,True
2,James,Warkentin,17,2,41,9,+7(529)642-87-60,True
1,Ana,Walker,17,9,23,10,+7(725)382-31-30,True

In [586]:
pd('Data2.xlsx').head??????

TypeError: 'module' object is not callable

In [600]:
df_1 = pd.read_excel('Data1.xlsx')
df_2 = pd.read_excel('Data2.xlsx')
df['Compare'] = df_1['Баллы'] <= df_1['Баллы']

In [601]:
df

,Имя,Фамилия,Возраст,№ выступления,Баллы,Призовое место,Телефон,Compare
1,Ana,Walker,17,9,23,10,+7(725)382-31-30,True
2,James,Warkentin,17,2,41,9,+7(529)642-87-60,True
3,Donald,Roman,5,10,43,8,+7(403)977-83-87,True
4,Debra,Simpson,18,7,47,7,+7(463)229-52-75,True
5,Anna,Barton,13,6,49,6,+7(885)328-88-19,True
6,Wilber,Bishop,5,8,60,5,+7(320)828-77-31,True
7,Anthony,Vanpelt,6,5,67,4,+7(756)293-98-74,True
8,Susan,Mays,12,4,71,3,+7(911)405-92-80,True
9,Shirley,Castillo,14,3,82,2,+7(608)889-72-21,True
10,Marian,Schleider,14,1,93,1,+7(438)778-94-17,NaN