In [1]:
import pandas as pd
import numpy as np
import names as n

In [2]:
pd.read_excel('Data1.xlsx')

,Unnamed: 0,Имя,Фамилия,Возраст,№ выступления,Баллы,Призовое место,Телефон
0,1,Lucienne,Hopkins,9,7,20,10,+7(268)865-27-26
1,2,Annette,Doyle,13,5,40,9,+7(137)886-83-57
2,3,Carolyn,Almanza,13,10,47,8,+7(335)474-30-58
3,4,Susie,Snyder,8,8,55,7,+7(211)416-55-26
4,5,Luella,Linton,7,9,55,6,+7(840)979-52-64
5,6,Ilene,Hibbler,10,3,56,5,+7(773)361-83-74
6,7,Lyman,Jackson,18,1,64,4,+7(767)697-26-53
7,8,Anita,Paya,13,6,96,3,+7(685)290-99-86
8,9,Corey,Ward,13,2,96,2,+7(635)743-81-45
9,10,Marion,Rodriguez,14,4,98,1,+7(227)475-46-19

In [3]:
index = np.arange(1, 11)

frame = {'Имя': [n.get_first_name() for i in range(len(index))],
        'Фамилия': [n.get_last_name() for i in range(len(index))],
        'Возраст': [np.random.randint(5,20) for i in range(len(index))]}

frame['№ выступления'] = []
while len(frame['№ выступления']) != len(index):
    for i in range(len(index)):
        k = np.random.randint(i,11)
        if k not in frame['№ выступления'] and k != 0:
            frame['№ выступления'].append(k)
        
frame['Баллы'] = [np.random.randint(20,100) for i in range(len(index))]

frame['Призовое место'] = []
k = 10
p = 11
frame['Баллы'].sort()
for i in range(len(frame['Баллы'])):
    if k <= frame['Баллы'][i]:
        k = frame['Баллы'][i]
        p -= 1
        frame['Призовое место'].append(p)
        
frame['Телефон'] = [("+7" + "(" + str(np.random.randint(100, 1000)) + ")" + str(np.random.randint(100, 1000)) + "-" + str(np.random.randint(10, 100)) + "-" + str(np.random.randint(10, 100))) for i in range(len(index))]

df = pd.DataFrame(frame, index)

df.to_excel('Data2.xlsx')

In [4]:
df.sort_values(by = 'Призовое место')

,Имя,Фамилия,Возраст,№ выступления,Баллы,Призовое место,Телефон
10,Cindy,Rose,7,1,80,1,+7(293)974-79-43
9,Jeffrey,Oconnor,5,6,68,2,+7(622)994-67-23
8,Patricia,Barker,15,9,51,3,+7(349)666-56-38
7,Salvatore,Boyd,5,8,49,4,+7(306)807-65-90
6,Jose,Woods,5,7,49,5,+7(452)646-77-62
5,Carol,Shinabarger,11,4,47,6,+7(505)761-75-89
4,Jeffrey,Mcfarlin,17,5,40,7,+7(877)213-29-95
3,Linda,Howell,14,2,37,8,+7(986)858-41-69
2,Joshua,Cook,13,10,32,9,+7(709)694-76-57
1,Judith,Rake,14,3,20,10,+7(430)164-63-90

In [5]:
df_1 = pd.read_excel('Data1.xlsx')
df_2 = pd.read_excel('Data2.xlsx')
df['Compare'] = df_1['Баллы'] <= df_1['Баллы']

In [6]:
df

,Имя,Фамилия,Возраст,№ выступления,Баллы,Призовое место,Телефон,Compare
1,Judith,Rake,14,3,20,10,+7(430)164-63-90,True
2,Joshua,Cook,13,10,32,9,+7(709)694-76-57,True
3,Linda,Howell,14,2,37,8,+7(986)858-41-69,True
4,Jeffrey,Mcfarlin,17,5,40,7,+7(877)213-29-95,True
5,Carol,Shinabarger,11,4,47,6,+7(505)761-75-89,True
6,Jose,Woods,5,7,49,5,+7(452)646-77-62,True
7,Salvatore,Boyd,5,8,49,4,+7(306)807-65-90,True
8,Patricia,Barker,15,9,51,3,+7(349)666-56-38,True
9,Jeffrey,Oconnor,5,6,68,2,+7(622)994-67-23,True
10,Cindy,Rose,7,1,80,1,+7(293)974-79-43,NaN